### ISSUE TITLE
menu bug. some settings at config menu are missing. especially pacenotes settings has issue

### ISSUE THREAD

**Issue by gRally-Issues** [gRally/dev#571] opened 2018-05-25 00:56 UTC
# User: oyunbozan
---

### [log](https://www.grally.net/u/uploads/e5fe3e79fcdc4bc96b792db681ac2134d280e8f2.zip)

`v1.0.3.1`

**Comment by ghiboz** [comment] 2018-05-25 07:35
duplicate of #537

**Closed by ghiboz** 2018-05-25 07:35 UTC
Labels: Duplicate
