### ISSUE TITLE
Game crashes after finishing stage

### ISSUE THREAD

**Issue by gRally-Issues** [gRally/dev#636] opened 2018-06-07 01:01 UTC
# User: AlenC
---

#### What happened?

Windows report that the game has crashed every time I finish the stage and click x to exit back to menus. However I can continue using menus normally.

#### Steps to reproduce:
Finish a stage and click on x to exit.

#### Happens one time or always?

Always

### [log](https://www.grally.net/u/uploads/c327b7b81d271fd6e2244e4c7e0ba5d0d27c517a.zip)

`v1.0.8.7`

**Comment by ghiboz** [comment] 2018-06-07 21:08
duplicate of #621

**Closed by ghiboz** 2018-06-07 21:08 UTC
Labels: Bug, Publish
