### ISSUE TITLE
Crash logs after finishing stage

### ISSUE THREAD

**Issue by gRally-Issues** [gRally/dev#607] opened 2018-05-30 00:38 UTC
# User: kevman_101
---

Crashes when finishing a stage

#### Considerations...

[crash](https://www.grally.net/u/uploads/e8800355adec720b3b26bf6cde26f92b181ea478.dmp)

[crash](https://www.grally.net/u/uploads/666bbeb490ae4ab68e06f5fd904ca0bbe061423f.dmp)

[error](https://www.grally.net/u/uploads/506525285fe98034d2f532c4895e56798045d7fe.log)

[error](https://www.grally.net/u/uploads/601f9f63e15e91bbf608ddc3ce453f3b0ca374fc.log)

### [log](https://www.grally.net/u/uploads/d53576343bfb0d4c3dc366d5492081f79e9b9872.zip)

`v1.0.5.4`

**Comment by ghiboz** [comment] 2018-05-30 17:03
duplicate of #602

**Closed by ghiboz** 2018-05-30 17:03 UTC
Labels: Bug, Duplicate
